apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-app
  namespace: pwc-app
  labels:
    app: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservices
  template:
    metadata:
      labels:
        app: microservices
    spec:
      containers:
      - name: microservices
        image: alyshaltout/pwc-microservices:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "65Mi"
            cpu: "50m"
          limits:
            memory: "65Mi"
            cpu: "50m"